# Site settings
baseurl: 'https://evanxd.io/blog'
title: 'Evan Tseng'
tagline: 'Creater | Developer | Gamer'
sidebar_image: /images/cover.jpg

# Build settings
markdown: redcarpet
highlighter: pygments
permalink: /:year/:month/:day/:title
