# Site settings
title: 'Evan Tseng'
tagline: 'JavaScript + Internet of Things Developer'
sidebar_image: /images/cover.jpg

# Build settings
markdown: redcarpet
highlighter: pygments
permalink: /:year/:month/:day/:title
