# Site settings
title: 'Evan Xd'
tagline: 'JavaScript + Internet of Things Hacker'
sidebar_image: /images/cover.jpg

# Build settings
markdown: redcarpet
highlighter: pygments
permalink: /:year/:month/:day/:title
source: https://evanxd.io/blog/
